Importe o pacote numpy com o nome np.


In [ ]:
import numpy as np
from io import StringIO

data = u"1, 2, 3\n4, 5, 6"
vetor = np.genfromtxt(StringIO(data), delimiter=",") # Converte dados para vetor
np.savetxt("nome_arquivo.txt", vetor, delimiter=" ")

Crie o seguinte vetor unidimensional (1D):


In [ ]:
import numpy as np 

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Crie o seguinte vetor unidimensional (1D):
0	1	2	3	4	5	6	7	8	9




In [ ]:
vet = np.array(range(10))
vet


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Qual é o comprimento len do vetor?


In [ ]:
print(len(vetor_numpy)) 

10


Quantas dimensões ndim o vetor possui?


In [ ]:
print(vetor_numpy.ndim)


1


O que a função shape retorna?


In [ ]:
print(vetor_numpy.shape) 

(10,)


Crie a variável pares e extraia todos os números pares do vetor para ela:


In [ ]:
vetpar = vet[vet % 2 == 0] 
vetpar


array([0, 2, 4, 6, 8])

Substitua todos os elementos ímpares do vetor por -1, em seguida, ordene os resultados:


In [ ]:
impar = vet[vet % 2 != 0] 

impar



array([-1, -1, -1, -1, -1])

Converta o vetor unidimensional (1D) abaixo para uma matriz (2D) com 4 linhas. Dica: reshape.


In [ ]:
vetor1d = np.arange(12)
newvetor = vetor1d.reshape(4,3)

newvetor


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Obtenha os itens em comum, ou seja, a intersecção dos vetores a e b abaixo:
Saída: [2, 4, 6]

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([2, 4, 6, 8, 10])

print(np.intersect1d(a, b))

[2 4 6]


Retorne os valores únicos do vetor a que não estão no vetor b (diferença).

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 4, 6, 8, 10])

print(np.setdiff1d(a,b))

[1 3]


Retorne um vetor com as posições (índices) onde os elementos do vetor a sãos iguais aos elementos do vetor b. Dica: where.


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([2, 4, 3, 4, 10, 6])

indices = np.where(a == b)
indices

(array([2, 3, 5]),)

Obtenha todos os itens entre 5 e 15 do vetor a = [0, 1, 2, 3, . . ., 20].

In [ ]:
a = np.arange(21)

np.where(np.logical_and(a>=6, a<=10))

(array([ 6,  7,  8,  9, 10]),)

Crie e imprima um vetor com 5 números aleatórios, sem seguida, obtenha os valores máximo e mínimo dele e mostre na tela.


In [ ]:
rand_nums = np.random.randint(100, size=(5))
min_num = np.min(rand_nums)
max_num = np.max(rand_nums)
print('O menor número é:', min_num)
print('O maior número é:', max_num)

O menor número é: 8
O maior número é: 45


Crie a seguinte matriz:
7	8	9
4	5	6
1	2	3


In [ ]:
matriz = np.array([[7,8,9],[4,5,6], [1,2,3]])
matriz

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

Troque de lugar a primeira coluna com a útltima coluna da matriz.

In [ ]:
newMatriz = matriz.copy()
matriz[:,0] = newMatriz[:,-1]
matriz[:,-1] = newMatriz[:,0]

matriz

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

Troque de lugar a primeira linha com a útltima linha da matriz.

In [ ]:
newMatriz = matriz.copy()
matriz[0,:] = newMatriz[-1,:]
matriz[-1,:] = newMatriz[0,:]

matriz

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

Crie uma matriz 7 × 5 preenchida com números decimais aleatórios entre 1 e 5.

In [ ]:
values = []
for i in range(7):
    values.append(np.random.uniform(0.0, 5.0, (5,)))

randomMatriz = np.array(values)
randomMatriz

array([[2.54874462, 2.19437237, 2.81013257, 2.0625865 , 2.72588849],
       [1.31823135, 3.64372196, 3.80828755, 2.03690099, 3.76195679],
       [3.28474138, 3.51588504, 0.14340572, 2.43994078, 1.56568355],
       [1.70102011, 0.69569546, 0.70885133, 0.76945006, 4.55520845],
       [0.85043584, 0.82463816, 4.81874197, 1.60215731, 4.71337714],
       [4.1143938 , 3.42035233, 2.57577223, 0.94369539, 0.94554869],
       [3.37859342, 3.99460084, 2.72724306, 4.59239107, 1.14280044]])

Qual é o comprimento len da matriz?

In [ ]:
len(randomMatriz)

7

Quantas dimensões ndim a matriz possui?

In [ ]:
np.ndim(randomMatriz)

2

O que a função shape retorna?

In [ ]:
np.shape(randomMatriz)

(7, 5)